# Generated by Django 5.2.13 on 2026-04-22 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('TT3+TA3', 'TT3+TA3 Interlink'), ('TT3+TA4', 'TT3+TA4 Superlink'), ('TD1+TA3', 'TD1+TA3 Rigid & Lowbed'), ('MULTI', 'Multi-Axle Modular')], max_length=20, unique=True)),
                ('description', models.CharField(max_length=120)),
                ('tare_kg', models.PositiveIntegerField()),
                ('gcm_kg', models.PositiveIntegerField(help_text='Gross Combination Mass')),
                ('group1_max_kg', models.PositiveIntegerField(default=7700, help_text='Steer axle max')),
                ('group2_max_kg', models.PositiveIntegerField(default=18000, help_text='Drive tandem max')),
                ('group3_max_kg', models.PositiveIntegerField(default=24000)),
                ('group4_max_kg', models.PositiveIntegerField(default=0)),
                ('group5_max_kg', models.PositiveIntegerField(default=0)),
                ('wheel_track_mm', models.PositiveIntegerField(default=1800)),
                ('default_tyre_load_kg', models.PositiveIntegerField(default=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet_number', models.CharField(max_length=40)),
                ('registration', models.CharField(max_length=20)),
                ('tare_kg_override', models.PositiveIntegerField(blank=True, help_text='Actual tare of this specific vehicle, if different from config default', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.vehicleconfig')),
            ],
            options={
                'ordering': ['fleet_number'],
                'unique_together': {('owner', 'fleet_number')},
            },
        ),
    ]
