# Generated by Django 5.2.17 on 2026-10-05 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("licence_number", models.CharField(max_length=40)),
                (
                    "prdp_number",
                    models.CharField(
                        blank=True,
                        help_text="Professional Driving Permit",
                        max_length=40,
                        verbose_name="PrDP number",
                    ),
                ),
                (
                    "operating_licence",
                    models.CharField(
                        blank=True,
                        help_text="NLTA e-hailing operating licence",
                        max_length=60,
                    ),
                ),
                ("vehicle_make", models.CharField(max_length=40)),
                ("vehicle_model", models.CharField(max_length=40)),
                ("vehicle_colour", models.CharField(max_length=30)),
                ("vehicle_plate", models.CharField(max_length=20, unique=True)),
                (
                    "vehicle_class",
                    models.CharField(
                        choices=[
                            ("economy", "Economy"),
                            ("comfort", "Comfort"),
                            ("xl", "XL (6 seats)"),
                        ],
                        default="economy",
                        max_length=10,
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("is_online", models.BooleanField(default=False)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                ("location_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("rider", "Rider"), ("driver", "Driver")],
                        default="rider",
                        max_length=10,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
