# Generated by Django 5.2.17 on 2026-10-05 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_class",
                    models.CharField(
                        choices=[
                            ("economy", "Economy"),
                            ("comfort", "Comfort"),
                            ("xl", "XL"),
                        ],
                        default="economy",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Finding a driver"),
                            ("accepted", "Driver on the way"),
                            ("arrived", "Driver has arrived"),
                            ("in_progress", "On trip"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "No drivers available"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("pickup_address", models.CharField(max_length=255)),
                ("pickup_lat", models.FloatField()),
                ("pickup_lng", models.FloatField()),
                ("dropoff_address", models.CharField(max_length=255)),
                ("dropoff_lat", models.FloatField()),
                ("dropoff_lng", models.FloatField()),
                ("est_distance_km", models.FloatField()),
                ("est_duration_min", models.FloatField()),
                (
                    "surge",
                    models.DecimalField(decimal_places=1, default=1, max_digits=3),
                ),
                ("fare_estimate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("actual_distance_km", models.FloatField(default=0)),
                (
                    "final_fare",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "platform_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "driver_earnings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("cash", "Cash"), ("card", "Card")],
                        default="cash",
                        max_length=10,
                    ),
                ),
                ("paid", models.BooleanField(default=False)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("arrived_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_by", models.CharField(blank=True, max_length=10)),
                (
                    "cancellation_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "rating_for_driver",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "rating_for_rider",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rides_as_driver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rides_as_rider",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "vehicle_class"],
                        name="rides_ride_status_187df1_idx",
                    )
                ],
            },
        ),
    ]
